### ISSUE TITLE
Creating "kables" from combined columns (gather)

### ISSUE THREAD

**Issue by kariljordan** [carpentries/public-survey-info#101]
The problem I'm having starts in line 788. Learners were asked which activities they're involved in and they check all that apply. I used gather (thanks Ben) to combine the columns. Now I want to make a table using **kable** that breaks down responses by percentage. I have the percentages, but can't figure out how to change the row names. I'd appreciate any help because there are about 4 other tables in this dataset that I'd like to create in this manner.

```{r}
# Data in columns 'Activities' through Column57
Continuous_Learning <- 
data %>%
  select(`Activities`:Column57) %>% 
  gather(col, Continuous_Learning) %>% 
  group_by(Continuous_Learning) %>% 
  tally() %>% 
  filter(!is.na(Continuous_Learning)) %>% 
  arrange(desc(n)) %>% 
  rename(`Continuous Learning Post-Workshop` = Continuous_Learning)

kable(Continuous_Learning, format = "markdown", row.names = FALSE, col.names = c("Continuous Learning", "n"))
my.prop <- round(prop.table(n) * 100)

kable(my.prop, format = "markdown", row.names = TRUE, col.names = c("%"))
#table(names,my.prop)

#How do I change the row names in the output table from 1, 2, 3, 4, 6, 6 to names <- c("Used non-Carpentry self-guided material.", 
#"Used self-guided Carpentry lesson material.", 
#"Participated in an in-person short course.", 
#"Participated in an online short course.", 
#"Participated in a Meetup.", 
#"Participated in a semester long course.")?
```

**Comment by kariljordan** [comment]
Here is the [RMD](https://github.com/carpentries/public-survey-info/blob/master/documents/reports/Carpentry-Reports/Long-Term-Feedback-Survey-Report/2017-04-17-carpentry-long-term-assessment-survey-report.rmd)

**Comment by benmarwick** [comment]
To add a column of percentages we can use mutate() like this:

```
# Data in columns 'Activities' through Column57
Continuous_Learning <- 
  data %>%
  select(`Activities`:Column57) %>% 
  gather(col, Continuous_Learning) %>% 
  group_by(Continuous_Learning) %>% 
  tally() %>% 
  mutate(perc = round(n / sum(n) * 100, 1)) %>% 
  filter(!is.na(Continuous_Learning)) %>% 
  arrange(desc(n)) %>% 
  rename(`Continuous Learning Post-Workshop` = Continuous_Learning)

kable(Continuous_Learning, 
      format = "markdown", 
      row.names = FALSE, 
      col.names = c("Continuous Learning", "n", "%"))

|Continuous Learning                         |   n|   %|
|:-------------------------------------------|---:|---:|
|Used non-Carpentry self-guided material.    | 127| 4.4|
|Used self-guided Carpentry lesson material. |  68| 2.4|
|Participated in an in-person short course.  |  59| 2.1|
|Participated in an online short course.     |  45| 1.6|
|Participated in a Meetup.                   |  35| 1.2|
|Participated in a semester long course.     |  24| 0.8|
```

Is that what you're after?

**Comment by benmarwick** [comment]
If you want to transpose this table so it's wide rather than long, we can do this:

```
Continuous_Learning_t <- as_data_frame(t(Continuous_Learning))
names(Continuous_Learning_t) <- Continuous_Learning_t[1,]
Continuous_Learning_t <- Continuous_Learning_t[-1, ]
row.names(Continuous_Learning_t) <- c("n", "%")

kable(Continuous_Learning_t)



|   |Used non-Carpentry self-guided material. |Used self-guided Carpentry lesson material. |Participated in an in-person short course. |Participated in an online short course. |Participated in a Meetup. |Participated in a semester long course. |
|:--|:----------------------------------------|:-------------------------------------------|:------------------------------------------|:---------------------------------------|:-------------------------|:---------------------------------------|
|n  |127                                      |68                                          |59                                         |45                                      |35                        |24                                      |
|%  |4.4                                      |2.4                                         |2.1                                        |1.6                                     |1.2                       |0.8                                     |

```

Some of the colnames have dashes in them, which the base functions can't handle as column names. So we use `dplyr::as_data_frame` and that takes care of it for us.

**Comment by kariljordan** [comment]
Hi @benmarwick! Thank you so much for this tip. My issue is that respondents were told to select all that apply, so is representing the information by percentage the best way to do this? So, for the first line 'Used non-Carpentry self-guided material.', 4.4% represents what exactly? I don't think that is the % of respondents who selected that option...

**Comment by benmarwick** [comment]
Right, it's 4.4% of all the responses provided for that survey question. Which is a number that is higher than the number of people responding, because each person can make multiple selections. But that's ok! You just say in your narrative that multiple selections were possible for this question, so the total number of responses is greater than the number of respondants. That's typical for simple reporting on multiple response analysis. We can do more, if you want, as I demonstrated over here: https://github.com/kariljordan/public-survey-info/issues/33
