### ISSUE TITLE
Link to rendered report

### ISSUE THREAD

**Issue by kariljordan** [carpentries/public-survey-info#84]
Hi @jduckles, do I need to update the link to the rendered report each time in the README? I thought it would update automatically when the file was changed.

**Comment by jduckles** [comment]
Shouldn't need to. I'm seeing some changes made. You will need to add and commit the `.html` file though. Sometimes if you check right away, it can take a few minute for the GitHub cache to refresh. Sometimes your browser's internal cache keeps showing the old version for awhile too.
