### ISSUE TITLE
Extreme likert values are missing from plot

### ISSUE THREAD

**Issue by jduckles** [carpentries/public-survey-info#87]
I do not see the colors for the extreme values "Strongly..." on this likert plot. Did none of the 400 respondents respond that way? I also don't see that anyone answered neutral. I suspect something is wrong here.

![image](https://cloud.githubusercontent.com/assets/119403/26037235/694b699a-3943-11e7-9751-4a73e4b1ae82.png)

**Comment by jduckles** [comment]
Digging into this its because this line had the wrong levels, so the levels that didn't match were being dropped from the plot.

```
order = c("Strongly Disagree", "Disagree", "Neither Agree nor Disagree", "Agree", "Strongly Agree")
```
Matching levels should be (renamed the variable to `levels` as well because order is a name of a function in base R:

```
levels = c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree")
```
Simplifying the whole block we can do:

```
cols_with_Agree <- map_lgl(data, ~`%in%`("Agree", .x))
data_agree <-  data[ , cols_with_Agree]

levels = c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree")

data_agree_likert <- likert(data.frame(lapply(data_agree, factor, levels, ordered=TRUE)))

title <- "Workshops are Welcoming & Useful"
theme_update(plot.title = element_text(hjust = 0.5))

plot(data_agree_likert)
```
to get

![image](https://cloud.githubusercontent.com/assets/119403/26171748/2e7c292c-3b9a-11e7-96c5-43b2804c2be1.png)

**Comment by kariljordan** [comment]
@jduckles Thank you so much Jonah for taking time to figure this out! I had this written on my list of "things to fix". I didn't realize 'order' was a function in R. I understand what you did! Learning so much. Thanks again.

**Comment by bduckles** [comment]
Jonah and I wrote a function that I used in the LikertJoin tutorial I sent you which both orders the factors based on the levels you set (my variable is factlevel). You need to make sure that you both set the factor level for the variable AND unify the factors. Otherwise if you have no responses in a factor level (ie. no one responds with "strongly disagree") it won't plot. 

' 
factfunc <- function(mydata, factlevel){
  factor(mydata, 
         levels=factlevel, 
         ordered = TRUE)
    fct_unify(mydata, 
              levels=factlevel) 
}
'

**Comment by kariljordan** [comment]
@benmarwick I wanted to make sure you saw these tips!

**Comment by benmarwick** [comment]
Thanks, good catch by @jduckles !
